#!/usr/bin/env bash
# This script displays listening TCP and UDP ports with their corresponding PID and program name

# Display listening TCP ports
echo Active Internet connections (only servers)
echo Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
netstat -tuln | awk '$1 == "tcp" && $NF != "0.0.0.0:*" && $NF != "127.0.0.1:*" {print $1, $2, $4, $5, $6}' | sed 's/:::/[::]/g' | sed 's/0.0.0.0:/\*:/' | sed 's/127.0.0.1:/localhost:/'

# Display listening UDP ports
echo Proto Recv-Q Send-Q Local Address           Foreign Address         PID/Program name
netstat -uln | awk '$1 == "udp" && $NF != "0.0.0.0:*" && $NF != "127.0.0.1:*" {print $1, $2, $4, $5, $NF}' | sed 's/:::/[::]/g' | sed 's/0.0.0.0:/\*:/' | sed 's/127.0.0.1:/localhost:/'
