#!/usr/bin/env bash
# Ensures Nginx is installed, running, and listening on port 80

if ! dpkg -l | grep -q nginx; then
    apt update -y
    apt install -y nginx
fi

systemctl start nginx

systemctl enable nginx

if command -v ufw &> /dev/null; then
    ufw allow 80/tcp
fi
