#!/usr/bin/env bash

sigterm_handler() 
{
    echo "I hate the kill command"
    cleanup
}

sigint_handler() 
{
    echo "Y U no love me?!"
}

sigquit_handler() 
{
    echo "Received SIGQUIT signal"
    cleanup
}

cleanup() 
{
    echo "Cleaning up..."
    rm -f /var/run/myscript.pid
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

PID=$$
echo $PID > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
