#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with sudo or as root."
    exit 1
fi

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts >/dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts >/dev/null

if command -v systemctl &>/dev/null; then
    systemctl restart systemd-resolved.service
elif command -v service &>/dev/null; then
    service network-manager restart
fi

echo "IP addresses updated successfully."
