#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

ipv4_addresses=$(ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -vE "^127|^0" | uniq)

echo "$ipv4_addresses"
