#!/usr/bin/env bash
# script should run the whoami command under the user passed as an argument and make sure to try your script by passing different users

sed -i '/^user/s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server/s/.*/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i '/listen \[::\]:80 default_server/s/.*/listen [::]:8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
